### ISSUE TITLE
Issue validating the Token 

### ISSUE THREAD

**Issue by maheshpabba** [marcospereirampj/python-keycloak#101]
Hi, I have an issue in validating the token. I am trying to introspect the token using python keycloak client and i get an error.

My Program: 

from gtapp import app
from flask import g, request
from keycloak import KeycloakOpenID
import requests
import json

keycloak_openid = KeycloakOpenID(server_url="http://docker1.getraind.com:8080/auth/",
                    client_id="CoreApp",
                    realm_name="Getraind",
                    client_secret_key="fafa4829-9909-4269-b2ab-a4e8501d3138")

@app.route('/')
def hello_world():
    if oidc.user_loggedin:
        return ('Hello, %s, <a href="/private">See private</a> '
                '<a href="/logout">Log out</a>') % \
            oidc.user_getfield('preferred_username')
    else:
        return 'Welcome anonymous, <a href="/private">Log in</a>'

@app.route('/private', methods=['POST','GET'])
def private():
    token = request.form.get('access_token')
    if token is None:
        token = request.args.get('access_token')
    if token is None:
        token = request.json.get('access_token')
    if not token:
        app.logger.error('No token submitted')
        return False
    print token
    # Introspect Token
    token_info = keycloak_openid.introspect(token['access_token'])
    return token_info

Error: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/server/gtapp/test.py", line 34, in private
    token_info = keycloak_openid.introspect(token['access_token'])
TypeError: string indices must be integers

Can anyone help me resolve this issue or point me in right direction on how to validate a token in python flask application?

**Comment by hariyerramsetty** [comment]
You are actually on the right path. I think you are using python 2.7. Try using python 3.0, its working for me.
