### ISSUE TITLE
keycloak.exceptions.KeycloakConnectionError: Can't connect to server (too many values to unpack (expected 2))

### ISSUE THREAD

**Issue by funfuck** [marcospereirampj/python-keycloak#125]
I want to use admin rest api "send_update_account".

Here is my code.

`keycloak_admin = KeycloakAdmin(server_url=os.getenv('KEYCLOAK_URI'),
                                username='admin',
                                password='admin',
                                verify=True)`
` keycloak_admin.send_update_account('78b1fa15-12c7-4122-9fc9-577a8ff171d4', ['UPDATE_PASSWORD'])`

**STACK TRACE**

`Traceback (most recent call last):
  File "/Users/tacko/sources/scg-id-flask/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tacko/sources/scg-id-flask/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/tacko/sources/scg-id-flask/routes/auth.py", line 22, in update_password
    res = keycloak_admin.send_update_account('78b1fa15-12c7-4122-9fc9-577a8ff171d4', ['UPDATE_PASSWORD'])
  File "/Users/tacko/sources/scg-id-flask/env/lib/python3.7/site-packages/keycloak/keycloak_admin.py", line 497, in send_update_account
    data=payload, **params_query)
  File "/Users/tacko/sources/scg-id-flask/env/lib/python3.7/site-packages/keycloak/keycloak_admin.py", line 1421, in raw_put
    r = self.connection.raw_put(*args, **kwargs)
  File "/Users/tacko/sources/scg-id-flask/env/lib/python3.7/site-packages/keycloak/connection.py", line 207, in raw_put
    "Can't connect to server (%s)" % e)
keycloak.exceptions.KeycloakConnectionError: Can't connect to server (too many values to unpack (expected 2))`

**Comment by funfuck** [comment]
Sorry about my incautious

My code need to be corrected like this
`keycloak_admin.send_update_account('78b1fa15-12c7-4122-9fc9-577a8ff171d4', json.dumps(['UPDATE_PASSWORD']))`
