### ISSUE TITLE
Decode token fails : No PEM start marker "b'-----BEGIN PRIVATE KEY-----'"

### ISSUE THREAD

**Issue by roastedcpu** [marcospereirampj/python-keycloak#153]
Hello,

Starting from the documentation example,
```
KEYCLOAK_PUBLIC_KEY = keycloak_openid.public_key()
print(KEYCLOAK_PUBLIC_KEY)
options = {"verify_signature": True, "verify_aud": True, "verify_exp": True}
token_info = keycloak_openid.decode_token(token['access_token'], key=KEYCLOAK_PUBLIC_KEY, options=options)
```
I'm facing the following issue while trying to validate the token signature:
``` jose.exceptions.JWKError: No PEM start marker "b'-----BEGIN PRIVATE KEY-----'" found ```

My public key looks okay, but even if I add '-----BEGIN PRIVATE KEY-----' to the beginning of the string, and also the END marker, it still raises this exception.

Python version: 3.9

I believe this has to do with the way the key is being passed to python-jose, but it's just a guess.

Could you please help me ?

Thank you

```
Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/rsa_backend.py", line 150, in __init__
    self._prepared_key = pyrsa.PublicKey.load_pkcs1(key)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/key.py", line 116, in load_pkcs1
    return method(keyfile)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/key.py", line 291, in _load_pkcs1_pem
    der = rsa.pem.load_pem(keyfile, 'RSA PUBLIC KEY')
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in load_pem
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in <listcomp>
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 75, in _pem_lines
    raise ValueError('No PEM start marker "%r" found' % pem_start)
ValueError: No PEM start marker "b'-----BEGIN RSA PUBLIC KEY-----'" found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/rsa_backend.py", line 153, in __init__
    self._prepared_key = pyrsa.PublicKey.load_pkcs1_openssl_pem(key)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/key.py", line 320, in load_pkcs1_openssl_pem
    der = rsa.pem.load_pem(keyfile, 'PUBLIC KEY')
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in load_pem
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in <listcomp>
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 75, in _pem_lines
    raise ValueError('No PEM start marker "%r" found' % pem_start)
ValueError: No PEM start marker "b'-----BEGIN PUBLIC KEY-----'" found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/rsa_backend.py", line 156, in __init__
    self._prepared_key = pyrsa.PrivateKey.load_pkcs1(key)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/key.py", line 116, in load_pkcs1
    return method(keyfile)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/key.py", line 563, in _load_pkcs1_pem
    der = rsa.pem.load_pem(keyfile, b'RSA PRIVATE KEY')
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in load_pem
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in <listcomp>
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 75, in _pem_lines
    raise ValueError('No PEM start marker "%r" found' % pem_start)
ValueError: No PEM start marker "b'-----BEGIN RSA PRIVATE KEY-----'" found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/rsa_backend.py", line 159, in __init__
    der = pyrsa_pem.load_pem(key, b'PRIVATE KEY')
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in load_pem
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 101, in <listcomp>
    pem_lines = [line for line in _pem_lines(contents, pem_start, pem_end)]
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/rsa/pem.py", line 75, in _pem_lines
    raise ValueError('No PEM start marker "%r" found' % pem_start)
ValueError: No PEM start marker "b'-----BEGIN PRIVATE KEY-----'" found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jwt.py", line 154, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jws.py", line 80, in verify
    _verify_signature(signing_input, header, signature, key, algorithms)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jws.py", line 268, in _verify_signature
    if not _sig_matches_keys(keys, signing_input, signature, alg):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jws.py", line 216, in _sig_matches_keys
    key = jwk.construct(key, alg)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jwk.py", line 60, in construct
    return key_class(key_data, algorithm)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/rsa_backend.py", line 169, in __init__
    raise JWKError(e)
jose.exceptions.JWKError: No PEM start marker "b'-----BEGIN PRIVATE KEY-----'" found

```

**Comment by roastedcpu** [comment]
Update: I am able to overcome this issue if I install python-jose[cryptography] version, but only to stumble on the following one:
```
Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/cryptography_backend.py", line 231, in __init__
    self.prepared_key = load_pem_public_key(key, self.cryptography_backend())
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 23, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1274, in load_pem_public_key
    self._handle_key_loading_error()
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1517, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/cryptography_backend.py", line 233, in __init__
    self.prepared_key = load_pem_private_key(key, password=None, backend=self.cryptography_backend())
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 18, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1244, in load_pem_private_key
    return self._load_key(
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1475, in _load_key
    self._handle_key_loading_error()
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1517, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jwt.py", line 154, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jws.py", line 80, in verify
    _verify_signature(signing_input, header, signature, key, algorithms)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jws.py", line 268, in _verify_signature
    if not _sig_matches_keys(keys, signing_input, signature, alg):
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jws.py", line 216, in _sig_matches_keys
    key = jwk.construct(key, alg)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/jwk.py", line 60, in construct
    return key_class(key_data, algorithm)
  File "/Users/john/Desktop/untitled/venv/lib/python3.9/site-packages/jose/backends/cryptography_backend.py", line 235, in __init__
    raise JWKError(e)
jose.exceptions.JWKError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
```

My public key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjzPBSzDTVSAtZKw/+uqNxQs6hWKonVWZxoH7hrBMVMMjrfDrWHRg+6x1TPFeT7trvacgBzk3AjpmtI/IFrEM2FbqgI9f4AtyQ0A/WRwEjSlGLoFod8V3Uq3WkTGQ50DHqwqTLlKR1y0SikQ4d6FsCmqcPOalhxuVN9p4DTKRsVzlgcuEHuXJ3/ueTo6PxCRrWQNG3g+Wj9Cwv+TVLRNOJVfVE+dwV+A2mm6bXbwSRzh486mjfzpHnCxDtH+2R8JXYRZ+65ujvmp67+IVoBsMg2i7wXpr1aXVhk5qyEIy3VvCfnW4Lb1VVrSLOWJw/E8d0vEhmG+95xWaFn2T4USu8QIDAQAB

**Comment by roastedcpu** [comment]
Solved: I uninstalled python-jose, installed python-jose[cryptography] and added -----BEGIN PUBLIC KEY----- and -----END PUBLIC KEY----- to the beginning and ending of the key, respectively.
