### ISSUE TITLE
Instantiating KeycloakAdmin triggers exception: Parameter client_assertion_type is missing

### ISSUE THREAD

**Issue by bjmc** [marcospereirampj/python-keycloak#192]
```python
>>> kc = KeycloakAdmin(
	server_url=KEYCLOAK_URL,
	username=USERNAME,
	password=PASSWORD,
	realm_name=REALM,
	verify=True
)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bjmc/.cache/pypoetry/virtualenvs/enian-api-82BW-_vl-py3.8/lib/python3.8/site-packages/keycloak/keycloak_admin.py", line 96, in __init__
    self.get_token()
  File "/home/bjmc/.cache/pypoetry/virtualenvs/enian-api-82BW-_vl-py3.8/lib/python3.8/site-packages/keycloak/keycloak_admin.py", line 1786, in get_token
    self._token = self.keycloak_openid.token(self.username, self.password, grant_type=grant_type)
  File "/home/bjmc/.cache/pypoetry/virtualenvs/enian-api-82BW-_vl-py3.8/lib/python3.8/site-packages/keycloak/keycloak_openid.py", line 201, in token
    return raise_error_from_response(data_raw, KeycloakGetError)
  File "/home/bjmc/.cache/pypoetry/virtualenvs/enian-api-82BW-_vl-py3.8/lib/python3.8/site-packages/keycloak/exceptions.py", line 106, in raise_error_from_response
    raise error(error_message=message,
keycloak.exceptions.KeycloakGetError: 400: b'{"error":"invalid_client","error_description":"Parameter client_assertion_type is missing"}'
```

I'm seeing this error trying to talk to a Keycloak v.12 server. I'm sure the credentials are valid because I've tested them using Python `requests` directly. For instance, this works:

```python
import requests

def create_admin_token():
    url = urljoin(KEYCLOAK_URL, 'realms/master/protocol/openid-connect/token')
    body = {
        'client_id': 'admin-cli',
        'grant_type': 'password',
        'username': USERNAME,
        'password': PASSWORD,
    }
    response = requests.post(url, data=body, allow_redirects=True)
    return response.json()['access_token']
```

**Comment by bjmc** [comment]
Oops, my mistake! For any other users stumbling on this issue: The trick was that I was setting the `realm_name` parameter to be the realm I want to administer, but because my admin user is part of the `'master'` realm, I also needed to pass a distinct [`user_realm_name` parameter](https://github.com/marcospereirampj/python-keycloak/blob/master/keycloak/keycloak_admin.py#L82).

Working incantation:

```python
keycloak_admin = KeycloakAdmin(
	server_url=KEYCLOAK_URL, 
	username=ADMIN_USERNAME,
	password=ADMIN_PASSWORD, 
	# ^ This admin user is part of the 'master' realm 
	user_realm_name='master',
	# But we want to use it to manage this realm:
	realm_name=REALM_TO_ADMIN, 
	verify=True
)
```

**Comment by double-a** [comment]
Please close if solved.
