### ISSUE TITLE
Could not deserialize key data with load_authorization_config

### ISSUE THREAD

**Issue by franciscodelgadodp** [marcospereirampj/python-keycloak#197]
Hello, I am trying to get the permissions and policies so I was following the documentation where it mentions that I should pass a json file. After exporting the Authorization Settings and saving it in a json file I try to load it but it marks me this error:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/jose/backends/cryptography_backend.py", line 231, in __init__
    self.prepared_key = load_pem_public_key(key, self.cryptography_backend())
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization/base.py", line 20, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1115, in load_pem_public_key
    self._handle_key_loading_error()
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1373, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
```

Does anyone knows what I am missing for this feature to work correctly?

**Comment by franciscodelgadodp** [comment]
After making some tests I discovered that it was not really the json but when calling the function to bring the policies:

`policies = keycloak_openid.get_policies(
    token['access_token'], method_token_info='decode', key=KEYCLOAK_PUBLIC_KEY)`
