### ISSUE TITLE
ImportError: No module named abc

### ISSUE THREAD

**Issue by zengqingfu1442** [marcospereirampj/python-keycloak#238]
python 2.7.18
pyhton-keycloak 0.26.1

```
>>> from keycloak import KeycloakAdmin
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keycloak/__init__.py", line 24, in <module>
    from .keycloak_admin import *
  File "/usr/local/lib/python2.7/dist-packages/keycloak/keycloak_admin.py", line 33, in <module>
    from .keycloak_openid import KeycloakOpenID
  File "/usr/local/lib/python2.7/dist-packages/keycloak/keycloak_openid.py", line 26, in <module>
    from jose import jwt
  File "/usr/local/lib/python2.7/dist-packages/jose/jwt.py", line 3, in <module>
    from collections.abc import Mapping
ImportError: No module named abc
```

**Comment by zengqingfu1442** [comment]
I see, `python-keycloak` does not support python2. 😭

**Comment by ryshoooo** [comment]
Hi @zengqingfu1442 

Unfortunately no and there are currently no plans on extending the support for Python 2. The support is currently for Python >= 3.7 and we intend to keep this support for as long as possible.

The error you are receiving is actually from a dependency library and it'd be quite a hassle to make jose support Python2.

I'll close this issue with a remark "Won't fix".
