### ISSUE TITLE
After upgrade to keycloak 17 --> RESTEASY003210: Could not find resource

### ISSUE THREAD

**Issue by DerGreul** [marcospereirampj/python-keycloak#273]
Hello,

To connect via API to my keycloak I'm using:

````
keycloak_admin = KeycloakAdmin(server_url="https://localhost:8443/auth/",
                               username='example-admin',
                               password='secret',
                               realm_name="master",
                               user_realm_name="only_if_other_realm_than_master",
                               verify=False,
                               auto_refresh_token=['get', 'put', 'post', 'delete']
)
````

Before upgrade to keycloak 17 it worked fine. Now I'm receiving the following error:

```
Traceback (most recent call last):
  File "C:\GIT\Keycloak User Administration\keycloak-user-management\create_user_dev.py", line 63, in <module>
    keycloak_admin = KeycloakAdmin(
  File "C:\Python38\lib\site-packages\keycloak\keycloak_admin.py", line 105, in __init__
    self.get_token()
  File "C:\Python38\lib\site-packages\keycloak\keycloak_admin.py", line 2289, in get_token
    self._token = self.keycloak_openid.token(self.username, self.password, grant_type=grant_type)    
  File "C:\Python38\lib\site-packages\keycloak\keycloak_openid.py", line 203, in token
    return raise_error_from_response(data_raw, KeycloakGetError)
  File "C:\Python38\lib\site-packages\keycloak\exceptions.py", line 106, in raise_error_from_response    raise error(error_message=message,
keycloak.exceptions.KeycloakGetError: 404: b'{"error":"RESTEASY003210: Could not find resource for full path: https://localhost:8443/auth/realms/master/protocol/openid-connect/token"}
```

Do you have a hint what I missed? Thank you for your help.

Best regards,
Michael

**Comment by samdammers** [comment]
@DerGreul just confirming KC17 amended the base path, it no longer includes /auth by default. Unless you set it explicitly? perhaps your issue?

**Comment by DerGreul** [comment]
Dear Sam,

thank you so much. That was exactly my problem.

**Comment by rafutek** [comment]
Hello, same issue here because I followed the README, it could be nice to update it, thanks !
