### ISSUE TITLE
keycloak.keycloak_admin.get_components query is not actually optional

### ISSUE THREAD

**Issue by FAUSheppy** [marcospereirampj/python-keycloak#278]
keycloak.keycloak_admin.get_components query parameter is indicated to be optional:

```
keycloak.KeycloakAdmin.raw_put(
Help on function get_components in module keycloak.keycloak_admin:

get_components(self, query=None)
    Return a list of components, filtered according to query parameters
    
    ComponentRepresentation
    https://www.keycloak.org/docs-api/8.0/rest-api/index.html#_componentrepresentation
    
    :param query: Query parameters (optional)
    :return: components list
```

But calling the function as-is leads to an error:

```
kc_admin.get_components()
[...]
Traceback (most recent call last):
  File "keycloak_config.py", line 96, in <module>
    print(kc_admin.get_components())
  File "/usr/local/lib/python3.7/dist-packages/keycloak/keycloak_admin.py", line 2113, in get_components
    data=None, **query)
TypeError: raw_get() argument after ** must be a mapping, not NoneType
```

Calling the function with an empty mapping instead works:

`kc_admin.get_components({})`

Suggestion: Change the default parameter to `{}` instead of `None` or make the parameter non-optional.

Using Keycloak 17.0.0.

**Comment by ryshoooo** [comment]
I believe this has been resolved with https://github.com/marcospereirampj/python-keycloak/commit/e56889e5dbbe9208a1ea76d5bb53ee4b039ee8f6
