### ISSUE TITLE
Any information on which versions of keycloak are supported?

### ISSUE THREAD

**Issue by ghost** [marcospereirampj/python-keycloak#319]
I cannot find it, and wonder if a version mismatch might be causing my issue. I am running 15.0.2.

My issue is I'm trying to use the library to access the keycloak admin panel, and this is my code:
```python
admin = keycloak.KeycloakAdmin(
	server_url=server_url,
	username='admin',
	password='...',
	realm_name='master',
	verify=False)
```
And the error is:
```
Traceback (most recent call last):
  File "app/t.py", line 14, in <module>
    admin = keycloak.KeycloakAdmin(
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/keycloak_admin.py", line 105, in __init__
    self.get_token()
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/keycloak_admin.py", line 2576, in get_token
    self.token = self.keycloak_openid.token(
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/keycloak_openid.py", line 229, in token
    return raise_error_from_response(data_raw, KeycloakGetError)
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/exceptions.py", line 118, in raise_error_from_response
    raise error(
keycloak.exceptions.KeycloakGetError: 404: b'<html><head><title>Error</title></head><body>404 - Not Found</body></html>'
```
I found a suggestion from another issue to append `/auth/admin/realms` to the server base URL, trying that led to:
```
Traceback (most recent call last):
  File "app/t.py", line 14, in <module>
    admin = keycloak.KeycloakAdmin(
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/keycloak_admin.py", line 105, in __init__
    self.get_token()
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/keycloak_admin.py", line 2576, in get_token
    self.token = self.keycloak_openid.token(
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/keycloak_openid.py", line 229, in token
    return raise_error_from_response(data_raw, KeycloakGetError)
  File "/home/yujiri/.local/share/virtualenvs/app-elU1QLpM/lib/python3.8/site-packages/keycloak/exceptions.py", line 118, in raise_error_from_response
    raise error(
keycloak.exceptions.KeycloakAuthenticationError: 401: b'{"error":"HTTP 401 Unauthorized"}'
```
Which seems more promising but I'm still not sure if that could be caused by a version issue. I am sure the username and password are correct.

**Comment by ghost** [comment]
Update: apparently the solution was fo me to put `auth/realms`, not `auth/admin/realms`, and *not* change the access type away from public as #132 said.

Would still be good to document what the supported versions of keycloak are.

**Comment by ryshoooo** [comment]
Hi @yujiri8 

In some honest sense, I do not really know at this time which Keycloak versions the library is supporting. What we are currently striving at is to always support the **latest** version of Keycloak. This is done by extensive unit testing and daily checks of the tests against the latest published Keycloak version.

When we have the full coverage of all the methods, I might spend some time and do the exercise to run all the tests against the previous Keycloak versions and see how far into the past they succeed.

**Comment by antoniolucasnobar** [comment]
Just FYI,

we use this library against Keycloak 12 without any problems. But we use mainly the keycloak_admin module, to create clients, users, groups and roles. We do not connect clients with it.

**Comment by ryshoooo** [comment]
It is a never-ending battle.

I've decided to only have active support for the latest 5 major versions of Keycloak. That doesn't mean the library does not support (in some way) older versions, but we will not pursue active development for Keycloak which is older than that.

You should also consider the fact that Keycloak only supports the latest major version (see https://endoflife.date/keycloak), so running older Keycloak versions will definitely not contain security patches and vulnerability fixes. So I'd overall recommend keeping the Keycloak version up-to-date :) and python-keycloak will follow
