### ISSUE TITLE
python-keycloak fails with keycloak 7.0.1

### ISSUE THREAD

**Issue by eurydice76** [marcospereirampj/python-keycloak#40]
Dear Marcos, 

I am using python-keycloak for setting up keycloak clients through python API. Recently, we switched from an old keycloak server (4.6.0) to a newer one (7.0.0). Since then, my script for setting up the client silently fails with an "403 unkown error". Here is my script:

```
import sys

from keycloak import KeycloakAdmin

if __name__ == "__main__":

    keycloak_admin = KeycloakAdmin(server_url="https://login.ill.fr/auth/",
                                   username="keycloak-user",
                                   password="blabla",
                                   realm_name="my-realm",
                                   verify=True)

    client_name = "test-client"
    client_ip = "192.168.13.207"
    client_port = "8080"

    visa_jupyter_client_id = keycloak_admin.get_client_id(client_name)
    if visa_jupyter_client_id:
        keycloak_admin.delete_client(visa_jupyter_client_id)

    _ = keycloak_admin.create_client({"clientId": client_name,
                                      "attributes":{"login_theme":"ill"},
                                      "name": client_name,
                                      "clientAuthenticatorType":"client-secret",
                                      "description":"my client",
                                      "consentRequired": False,
                                      "publicClient": False,
                                      "baseUrl": "/",
                                      "protocol":"openid-connect",
                                      "rootUrl":"http://%s:%s" % (client_ip,client_port),
                                      "redirectUris":["*"],
                                      "webOrigins":[],
                                      "adminUrl": "",
                                      "serviceAccountsEnabled": True,
                                      "enabled": True}, skip_exists=True)

    visa_jupyter_client_id = keycloak_admin.get_client_id(client_name)

    client_info = {"id":client_name, "secret":keycloak_admin.get_client_secrets(visa_jupyter_client_id)["value"]}

    print(client_info)
```

And here is the traceback I get when running that script with our newer keycloak server:

```
Traceback (most recent call last):
  File "get_client_new_api.py", line 36, in <module>
    "enabled": True}, skip_exists=True)
  File "/home/pellegrini/.local/lib/python3.6/site-packages/keycloak/keycloak_admin.py", line 686, in create_client
    return raise_error_from_response(data_raw, KeycloakGetError, expected_code=201, skip_exists=skip_exists)
  File "/home/pellegrini/.local/lib/python3.6/site-packages/keycloak/exceptions.py", line 102, in raise_error_from_response
    response_body=response.content)
keycloak.exceptions.KeycloakGetError: 403: b'{"error":"unknown_error"}'
```

Would you have any idea why this script turned to fail with keycloak v7.0.1 ?

Many thanks in advance for your help

**EDIT:** the following simpler example taken from the docs also fails with keycloak 7.0.1:

```
import sys

from keycloak import KeycloakAdmin

if __name__ == "__main__":

    keycloak_admin = KeycloakAdmin(server_url="https://login.ill.fr/auth/",
                                   username="keycloak-user",
                                   password="blabla",
                                   realm_name="my-realm",
                                   verify=True)

    print(keycloak_admin.users_count())

```

**Comment by eurydice76** [comment]
Sorry, my bad, I forgot to update the user role mappings with realm_admin right. Everything is fine with now. Sorry for the inconvenience.
