### ISSUE TITLE
httpx proxy parameter

### ISSUE THREAD

**Issue by virgiled-bull** [marcospereirampj/python-keycloak#623]
Hello @marcospereirampj , very nice library you created here.
I encountered a problem while using it through codespace on github:

python-keycloak version is 4.7.1

> Traceback (most recent call last):
>
>	  File "/workspaces/sonar-migration/populate_keycloak.py", line 190, in <module>
>		main()
>	  File "/workspaces/sonar-migration/populate_keycloak.py", line 142, in main
>		kc_handler = configure()
>	  File "/workspaces/sonar-migration/populate_keycloak.py", line 51, in configure
>		keycloak_connection = KeycloakOpenIDConnection(
>	  File "/workspaces/sonar-migration/.venv/lib/python3.10/site-packages/keycloak/openid_connection.py", line 141, in __init__
>		super().__init__(
>	  File "/workspaces/sonar-migration/.venv/lib/python3.10/site-packages/keycloak/connection.py", line 105, in __init__
>		self.async_s = httpx.AsyncClient(verify=verify, proxies=proxies, cert=cert)
>	TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'

I suppose that in codespace there are some HTTP(S)_PROXY env vars set that httpx respects, I must admint I'm a bit confused by the fact that it works on my machine...

Anyway, the fact is that httpx.AsyncClient has no "proxies" argument, only a "proxy" one (cf AsyncClient in [https://www.python-httpx.org/api/](https://www.python-httpx.org/api/))
Don't know if that changed recently, Im surprised that it was not noticed before.

Any thoughts?

**Comment by Thodorissio** [comment]
Hello I had the same issue so I downgraded the python-keycloak to 4.0.0 to make my app work. (I didnt test for higher versions - they might work as well)

**Comment by ryshoooo** [comment]
Hi @virgiled-eviden 

This has been fixed with https://github.com/marcospereirampj/python-keycloak/pull/622/files and released in version 4.7.3, thus upgrading the version of python-keycloak should do the trick. The reason it works for you is likely due to the older version of httpx library, where `proxies` argument was supported, however in the latest versions it is not.
