### ISSUE TITLE
ValueError: Could not deserialize key data.

### ISSUE THREAD

**Issue by nikhiljha** [marcospereirampj/python-keycloak#88]
keycloak 10, python-keycloak 0.20.0, python 3.7

```python3
from keycloak import KeycloakOpenID

# Configure client
keycloak_openid = KeycloakOpenID(server_url="https://path/to/my/server", client_id="ocfapi", realm_name="ocf", client_secret_key="my-secret-key")

# Get WellKnow
config_well_know = keycloak_openid.well_know()

# Get Token
token = keycloak_openid.token("username", "password")

print(token)
print(type(token))

# error happens somewhere after here

KEYCLOAK_PUBLIC_KEY = keycloak_openid.public_key()
options = {"verify_signature": True, "verify_aud": True, "exp": True}
token_info = keycloak_openid.decode_token(token['access_token'], key=KEYCLOAK_PUBLIC_KEY, options=options)

print(token_info)
```

Gives the error...

```
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/jose/backends/cryptography_backend.py", line 236, in __init__
    self.prepared_key = load_pem_public_key(key, self.cryptography_backend())
  File "/lib/python3.7/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 20, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1077, in load_pem_public_key
    self._handle_key_loading_error()
  File "/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1335, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.
```

Setting `"verify_signature": False` makes this work as expected.

**Comment by nikhiljha** [comment]
Solved, just do
```python3
KEYCLOAK_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\n" + KEYCLOAK_PUBLIC_KEY + "\n-----END PUBLIC KEY-----"
```

This probably should be a default, but I'm going to close this since it should be easy to Google.

**Comment by PierreKelbert** [comment]
I think it would be useful to make decode_token compatible with this public key format and doing a PR look be the right way :)
