### ISSUE TITLE
Keycloak 4.5 user password set error

### ISSUE THREAD

**Issue by marcospereirampj** [marcospereirampj/python-keycloak#9]
Hi, since I was working with Keycloak 4.4 my python script works, but with KC 4.5 : Traceback (most recent call last): File "./KC_CreateFakeUsers.py", line 25, in <module> password = keycloak_admin.set_user_password(user_id="stress"+str(x), password="secret", temporary=False) File "/usr/local/lib/python3.6/dist-packages/keycloak/keycloak_admin.py", line 233, in set_user_password return raise_error_from_response(data_raw, KeycloakGetError, expected_code=204) File "/usr/local/lib/python3.6/dist-packages/keycloak/exceptions.py", line 93, in raise_error_from_response response_body=response.content) keycloak.exceptions.KeycloakGetError: 404: b''

Is there a change in KC 4.5 api url ?

**Comment by marcospereirampj** [comment]
In version 4.5, the base path was changed.

Before version 4.5: "https://{server-url}/auth/admin/"
After version 4.5: "https://{server-url}/auth/"

**Comment by marcospereirampj** [comment]
`
keycloak_admin.set_user_password(user_id="stress"+str(x), password="secret", temporary=False)
`

The error is in `user_id="stress"+str(x)`. What is "stress"?
